
Alerte:
  definition:
    fields:
      _id: {  }
      _rev: {  }
      type: {  }
      sous_type: {  }
      interpro: {  }
      etablissement_identifiant: {  }
      alertes:
        type: collection
        definition:
          fields:
            '*':
              type: collection
              definition:
                fields:
                  detail: {  }
                  commentaire: {  }
                  statut: {  }
      derniere_detection: {  }
